apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeting-apis-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: { { .Values.ingress.host } }
      http:
        paths:
          - path: /dotnet/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: dotnet-api
                port:
                  number: 80
          - path: /go/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: go-api
                port:
                  number: 80
          - path: /nodejs/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: nodejs-api
                port:
                  number: 80
          - path: /rails/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: rails-api
                port:
                  number: 80
