{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: greeting-apis-ingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /dotnet/
            pathType: Prefix
            backend:
              service:
                name: dotnet-api
                port:
                  number: 80
          - path: /go/
            pathType: Prefix
            backend:
              service:
                name: go-api
                port:
                  number: 80
          - path: /nodejs/
            pathType: Prefix
            backend:
              service:
                name: nodejs-api
                port:
                  number: 80
          - path: /rails/
            pathType: Prefix
            backend:
              service:
                name: rails-api
                port:
                  number: 80
{{- end }}